### PR TITLE
Dev/sprint4

### PR DESCRIPTION
**Pull request by a-iacampo**
# Description
Final merge into master
Merge includes:
- 3 core features: (Upload pictures #17, Follow users #18, Like and Comment #16)
- 2 extra features: (Edit profile info #46, Search for other users #89)
- Delete pictures #90
- Sign in/Sign up page #38
- Main user profile page #20  #36

### CODE REVIEW

**Review by Jordan-Hum — APPROVED** [review]
good

**Review by Eltom777 — APPROVED** [review]
we're done boys !!! 🥇

**Review by digathomas — APPROVED** [review]
Everything works together! great job

**Review by Swnoob — APPROVED** [review]

**Comment by Swnoob** [comment]
good

**Pull request merged**
