### PR TITLE
Merge test

### PR DESCRIPTION
**Pull request by a-iacampo**
#123 #118

### CODE REVIEW

**Review by Eltom777 — APPROVED** [review]
looks good to me !

**Review by Jordan-Hum — APPROVED** [review]
nice

**Comment by Eltom777** [comment]
comment out your unit test. If you look at the travis console, your having the same async issue as all the other tests. 

Need to implement the test using a mock function

**Comment by Eltom777** [comment]
For now, add the flag --forceExit to Jest

**Pull request merged**
