### PR TITLE
Dev/adjust posting picture with auth user #101

### PR DESCRIPTION
**Pull request by Eltom777**
- Pictures will be uploaded to the logged in users
- Add the likes counts to newly created images inside the database

### CODE REVIEW

**Review by a-iacampo — APPROVED** [review]
Looks good. Nice job!

**Review by a-iacampo — CHANGES_REQUESTED** [review]
However, there seems to be a conflict with the imports in AddPhoto.jsx

**Review by a-iacampo — APPROVED** [review]
Conflicts resolved.

**Review by Jordan-Hum — APPROVED** [review]
Looks good thanks

**Pull request merged**
