### PR TITLE
Created .travis.yml to initialize travis CI in our repository. #29

### PR DESCRIPTION
**Pull request by Eltom777**
Implemented travis ci in our repo. In the future, this CI tool will run all our tests automatically after every push to master. 

If you have the time please go over: unit tests and travis ci

### CODE REVIEW

**Comment by a-iacampo** [comment]
Why is the build failing?

**Comment by Eltom777** [comment]
If you look at the console, travis wasn't able to find tests. As a result, it failed. 
I will try to implement javamocha in our repo and create a folder called tests.

**Comment by Eltom777** [comment]
Youpiiiii !!!! our first tested passed

**Comment by Eltom777** [comment]
Proof:
passed

**Comment by a-iacampo** [comment]
🥇 💯

**Review by a-iacampo — APPROVED** [review]
Approved 👍

**Review by Jordan-Hum — APPROVED** [review]
👑 approved 🌭

**Comment by digathomas** [comment]
Very nice!

**Pull request merged**
